// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WorkingClient is the client API for Working service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkingClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error)
}

type workingClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkingClient(cc grpc.ClientConnInterface) WorkingClient {
	return &workingClient{cc}
}

func (c *workingClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/task_system.scheduler.v1.Working/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkingServer is the server API for Working service.
// All implementations must embed UnimplementedWorkingServer
// for forward compatibility
type WorkingServer interface {
	Ping(context.Context, *Empty) (*Result, error)
	mustEmbedUnimplementedWorkingServer()
}

// UnimplementedWorkingServer must be embedded to have forward compatible implementations.
type UnimplementedWorkingServer struct {
}

func (UnimplementedWorkingServer) Ping(context.Context, *Empty) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWorkingServer) mustEmbedUnimplementedWorkingServer() {}

// UnsafeWorkingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkingServer will
// result in compilation errors.
type UnsafeWorkingServer interface {
	mustEmbedUnimplementedWorkingServer()
}

func RegisterWorkingServer(s grpc.ServiceRegistrar, srv WorkingServer) {
	s.RegisterService(&Working_ServiceDesc, srv)
}

func _Working_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task_system.scheduler.v1.Working/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkingServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Working_ServiceDesc is the grpc.ServiceDesc for Working service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Working_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task_system.scheduler.v1.Working",
	HandlerType: (*WorkingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Working_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/working.proto",
}
